apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE}-config
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: "${IMG_TAG}"
data:
  DEPLOYMENT_ENV: ${DEPLOYMENT_ENV}
  DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
  ASPNETCORE_HTTP_PORTS: "${API_MS_PORT}"
  MONGO_DB_NAME: ${MONGO_DB_NAME}
  MONGO_COL_NAME: ${MONGO_COL_NAME}
  LD_CONTEXT_NAME: ${LD_CONTEXT_NAME}
  LD_API_ACTIVE_KEY: ${LD_API_ACTIVE_KEY}
  LOG_DESTINATION_HOST: "${LOG_DESTINATION_HOST}"
  LOG_DESTINATION_PORT: "${LOG_DESTINATION_PORT}"
  SERVICE_NAME: ${SERVICE}
  SERVICE_VERSION: "${IMG_TAG}"
  PROJECT_NAME: ${PROJECT_NAME}
  LOG_LEVEL: ${LOG_LEVEL}
  TRACE_ID_REQ_HEADER: ${TRACE_ID_REQ_HEADER}