apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE}-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: ${IMG_TAG}
  type: Opaque
data:
  MONGO_CON_STR: ${MONGO_CON_STR}
  LD_ENV_SDK_KEY: ${LD_ENV_SDK_KEY}
  LD_CONTEXT_API_KEY: ${LD_CONTEXT_API_KEY}