apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: ${SERVICE}-config
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: ${NAMESPACE}
resources:
  - namespace.yaml
  - secret.yaml
  - helmrelease.yaml
