apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE}-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: ${REDIS_HELM_CHART_VERSION}
  type: Opaque
data:
  redis-password: ${NOTIFICATION_REDIS_PW}
