services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0-597b6f20-SNAPSHOT
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health | grep -E '"status":"(green|yellow)"' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.0-597b6f20-SNAPSHOT
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/5080 && exit 0 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elk
      - myapp_shared

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.0-597b6f20-SNAPSHOT
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "${KIBANA_PORT:-9003}:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
  myapp_shared:
    external: true