services:
  # dblistener:
  #   build:
  #     context: ../../
  #     dockerfile: ./src/DbListener/Dockerfile
  #   container_name: "dblistener"
  #   restart: on-failure
  # depends_on:
  #   - mongodb
  # networks:
  #   - db

  api:
    build:
      context: ../../
      dockerfile: ./src/Api/Dockerfile
    container_name: "api"
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=10000
      - MONGO_CON_STR=mongodb://admin:pw@mongodb:27017/admin?authMechanism=SCRAM-SHA-256&replicaSet=rs0
    ports:
      - 10000:10000
    networks:
      - db

  mongodb:
    image: mongo:8-noble
    entrypoint:
      - bash
      - -c
      - |
        openssl rand -base64 756 > /replica.key
        chmod 400 /replica.key
        chown 999:999 /replica.key
        exec docker-entrypoint.sh $$@
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017", "-keyFile", "/replica.key" ]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    container_name: "mongodb"
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pw
      - MONGO_INITDB_DATABASE=RefData
    networks:
      - db

  # Used to start the replica set in the MongoDb instance (will run once and exit)
  db-init:
    image: mongo:8-noble
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --username admin --password pw --host mongodb:27017 --eval ' rs.initiate( {
         _id : "rs0",
         members: [
            { _id: 0, host: "mongodb:27017" }
         ]
      }) '
    networks:
      - db

  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=pw
      - ME_CONFIG_BASICAUTH_USERNAME=appUser
      - ME_CONFIG_BASICAUTH_PASSWORD=appPw
      - ME_CONFIG_MONGODB_URL=mongodb://admin:pw@mongodb:27017/?replicaSet=rs0
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "9000:8081"
    networks:
      - db

networks:
  db:
