services:
  notification:
    build:
      context: ../../
      dockerfile: ./src/Notification/Dockerfile
    container_name: "notification"
    restart: on-failure
    depends_on:
      notification_db:
        condition: service_healthy
      dblistener_db:
        condition: service_healthy
    environment:
      - DOTNET_ENVIRONMENT=Development
      - REDIS_CON_STR=notification_db:6379
      - REDIS_CON_STR_QUEUE=dblistener_db:6379
      - API_BASE_URL=http://api:10000
    networks:
      - notification
      - notificationDb
      - dblistenerDb
      - api

  notification_db:
    image: redis:7-alpine
    container_name: "notification_db"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - notificationDb

  dblistener:
    build:
      context: ../../
      dockerfile: ./src/DbListener/Dockerfile
    container_name: "dblistener"
    restart: on-failure
    depends_on:
      dblistener_db:
        condition: service_healthy
      api_db:
        condition: service_healthy
    environment:
      - DOTNET_ENVIRONMENT=Development
      - MONGO_CON_STR=mongodb://${API_DB_ADMIN_USER:-admin}:${API_DB_ADMIN_PW:-pw}@api_db:27017/admin?authMechanism=SCRAM-SHA-256&replicaSet=rs0
      - REDIS_CON_STR=dblistener_db:6379
    networks:
      - dblistener
      - dblistenerDb
      - apiDb

  dblistener_db:
    image: redis:7-alpine
    container_name: "dblistener_db"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - dblistener
      - dblistenerDb

  redis_gui:
    image: redislabs/redisinsight:latest
    container_name: "redis_gui"
    restart: on-failure
    depends_on:
      dblistener_db:
        condition: service_healthy
    ports:
      - ${REDIS_GUI_PORT:-9001}:5540
    networks:
      - dblistenerDb
      - notificationDb

  api:
    build:
      context: ../../
      dockerfile: ./src/Api/Dockerfile
    container_name: "api"
    restart: on-failure
    depends_on:
      api_db:
        condition: service_healthy
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=10000
      - MONGO_CON_STR=mongodb://${API_DB_ADMIN_USER:-admin}:${API_DB_ADMIN_PW:-pw}@api_db:27017/admin?authMechanism=SCRAM-SHA-256&replicaSet=rs0
    ports:
      - ${API_PORT:-10000}:10000
    networks:
      - api

  api_db:
    image: mongo:8-noble
    entrypoint:
      - bash
      - -c
      - |
        openssl rand -base64 756 > /replica.key
        chmod 400 /replica.key
        chown 999:999 /replica.key
        exec docker-entrypoint.sh $$@
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017", "-keyFile", "/replica.key" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    container_name: "api_db"
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${API_DB_ADMIN_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${API_DB_ADMIN_PW:-pw}
      - MONGO_INITDB_DATABASE=RefData
    networks:
      - api
      - apiDb

  # Used to start the replica set in the MongoDb instance (will run once and exit)
  db_init:
    image: mongo:8-noble
    container_name: "db_init"
    restart: "no"
    depends_on:
      api_db:
        condition: service_healthy
    command: >
      mongosh --username ${API_DB_ADMIN_USER:-admin} --password ${API_DB_ADMIN_PW:-pw} --host api_db:27017 --eval ' rs.initiate( {
         _id : "rs0",
         members: [
            { _id: 0, host: "api_db:27017" }
         ]
      }) '
    networks:
      - apiDb

  api_db_gui:
    image: mongo-express:latest
    container_name: "api_db_gui"
    environment:
      - ME_CONFIG_MONGODB_SERVER=api_db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${API_DB_ADMIN_USER:-admin}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${API_DB_ADMIN_PW:-pw}
      - ME_CONFIG_BASICAUTH_USERNAME=appUser
      - ME_CONFIG_BASICAUTH_PASSWORD=appPw
      - ME_CONFIG_MONGODB_URL=mongodb://${API_DB_ADMIN_USER:-admin}:${API_DB_ADMIN_PW:-pw}@api_db:27017/?replicaSet=rs0
    depends_on:
      api_db:
        condition: service_healthy
    ports:
      - ${MONGO_GUI_PORT:-9000}:8081
    networks:
      - apiDb
  
  webhook_server:
    build:
      context: ../../
      dockerfile: ./setup/local/webhook/Dockerfile
    container_name: "webhook_server"
    restart: on-failure
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=10000
    ports:
      - ${WEBHOOK_API_PORT:-10001}:10000
    networks:
      - notification

networks:
  api:
  apiDb:
  dblistener:
  dblistenerDb:
  notification:
  notificationDb:
