apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE}-deployment
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: ${IMG_TAG}
spec:
  selector:
    matchLabels:
      app: ${SERVICE}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ${SERVICE}
        env: ${ENVIRONMENT}
        version: ${IMG_TAG}
    spec:
      serviceAccountName: ${SERVICE}-service-account
      containers:
        - name: ${SERVICE}
          image: ${IMG_NAME}:${IMG_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: ${API_MS_PORT}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          envFrom:
            - configMapRef:
              name: ${SERVICE}-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"