apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE}-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: ${IMG_TAG}
  type: Opaque
data:
  KAFKA_BROKER_SASL_USERNAME: ${KAFKA_BROKER_SASL_USERNAME}
  KAFKA_BROKER_SASL_PW: ${KAFKA_BROKER_SASL_PW}
  KAFKA_SCHEMA_REGISTRY_SASL_USERNAME: ${KAFKA_SCHEMA_REGISTRY_SASL_USERNAME}
  KAFKA_SCHEMA_REGISTRY_SASL_PW: ${KAFKA_SCHEMA_REGISTRY_SASL_PW}
  LD_ENV_SDK_KEY: ${LD_ENV_SDK_KEY}
  LD_CONTEXT_API_KEY: ${LD_CONTEXT_API_KEY}