apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${NAMESPACE}
resources:
  - secret.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: ${SERVICE}-config
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml